#!/usr/bin/python
# -*- coding:utf-8 -*-
import socket, struct, telnetlib,string
import itertools

# --- common funcs ---
def sock(remoteip, remoteport):
  s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  s.connect((remoteip, remoteport))
  return s, s.makefile('rw', bufsize=0)

def read_until(f, delim='\n'):
  data = ''
  while not data.endswith(delim):
    data += f.read(1)
  return data

def shell(s):
  t = telnetlib.Telnet()
  t.sock = s
  t.interact()

def get_cookie(username):
    read_until(f, "whitespace):")
    s.send(username+"\n")
    read_until(f, "is: ")
    return read_until(f).strip()

def p(a): return struct.pack("<I",a)
def u(a): return struct.unpack("<I",a)[0]

# --- main ---
HOST, PORT = "52.193.157.19" , 9999
s, f = sock(HOST, PORT)    # 接続
text = read_until(f, "XXXX:")
text = text.split('==')
hash_from4 = text[0].split("+")[1].strip()[:-1]
hash = text[1].split("\n")[0].strip()

for i in itertools.product(string.ascii_letters + string.digits, repeat=4):
    pr = "".join(i) + hash_from4
    if SHA256.new(pr).hexdigest() == hash:
        print "".join(i)
        
    

